
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  java:
    name: Java/Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: gradle-build-plugins

      # Setup Gradle properties, heap requirements are for the "Integration test w/ Nessie".
      - name: Setup gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8" >> ~/.gradle/gradle.properties
          echo "org.gradle.vfs.watch=false" >> ~/.gradle/gradle.properties

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: gradle-build-plugins
          arguments: assemble check publishToMavenLocal

      - name: Clone Nessie for integration test
        uses: actions/checkout@v3
        with:
          repository: projectnessie/nessie
          ref: main
          path: nessie
